CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    clave VARCHAR(255) NOT NULL,
    rol VARCHAR(20) DEFAULT 'admin', -- 'admin', 'mesero'
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
